apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: openshift-gitops
  labels:
    app-type: nginx
spec:
  destination:
    namespace: lbg-ocp-engineering-100-lab
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/
    repoURL: https://github.com/glaceroy/nginx.git
    targetRevision: HEAD
    helm:
      version: v3
      valuesFile:
        - helm/values.yaml
  info:
    - name: 'Purpose'
      value: 'Application to test istio use cases'
  syncPolicy:
    automated: {}
