namespace: lbg-ocp-engineering-100-lab

hostname: nginx-smesh.apps.ocp.cloud.lab

replicaCount: 1

image:
  repository: utility.cloud.lab:8443/nginx/nginx-unprivileged
  pullPolicy: IfNotPresent
  tag: latest

podAnnotations:
  sidecar.istio.io/inject: "true"

podLabels:
  app: nginx
  version: v1

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http


